// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPkL_QgRZ6cLPhH0FOulo50e4wDu9Ve-I',
    appId: '1:8878044441:web:0a7f7b862241ef35ec4188',
    messagingSenderId: '8878044441',
    projectId: 'periodtrack-955f2',
    authDomain: 'periodtrack-955f2.firebaseapp.com',
    storageBucket: 'periodtrack-955f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnlYC8QrP6BS20CbWE-hSVD3N9t2kBazE',
    appId: '1:8878044441:android:2b8d6eec46dda33bec4188',
    messagingSenderId: '8878044441',
    projectId: 'periodtrack-955f2',
    storageBucket: 'periodtrack-955f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJnJwNJywHucGW00PjupKwYIBn4Dtkv3k',
    appId: '1:8878044441:ios:72909dcc6a8b6506ec4188',
    messagingSenderId: '8878044441',
    projectId: 'periodtrack-955f2',
    storageBucket: 'periodtrack-955f2.appspot.com',
    iosClientId: '8878044441-qn53i9erv3b2pi1lsdrodvdo1dqu56ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.periodTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJnJwNJywHucGW00PjupKwYIBn4Dtkv3k',
    appId: '1:8878044441:ios:72909dcc6a8b6506ec4188',
    messagingSenderId: '8878044441',
    projectId: 'periodtrack-955f2',
    storageBucket: 'periodtrack-955f2.appspot.com',
    iosClientId: '8878044441-qn53i9erv3b2pi1lsdrodvdo1dqu56ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.periodTrack',
  );
}
